/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPasswordResetAudit;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualPasswordResetAuditRecord extends UpdatableRecordImpl<IndividualPasswordResetAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual_password_reset_audit.id</code>.
     */
    public IndividualPasswordResetAuditRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual_password_reset_audit.individual_id</code>.
     */
    public IndividualPasswordResetAuditRecord setIndividualId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.individual_id</code>.
     */
    public UUID getIndividualId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>individual_password_reset_audit.email</code>.
     */
    public IndividualPasswordResetAuditRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>individual_password_reset_audit.reset_link</code>.
     */
    public IndividualPasswordResetAuditRecord setResetLink(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.reset_link</code>.
     */
    public String getResetLink() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>individual_password_reset_audit.reset_link_requested_at</code>.
     */
    public IndividualPasswordResetAuditRecord setResetLinkRequestedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_password_reset_audit.reset_link_requested_at</code>.
     */
    public LocalDateTime getResetLinkRequestedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for
     * <code>individual_password_reset_audit.reset_link_expires_at</code>.
     */
    public IndividualPasswordResetAuditRecord setResetLinkExpiresAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_password_reset_audit.reset_link_expires_at</code>.
     */
    public LocalDateTime getResetLinkExpiresAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for
     * <code>individual_password_reset_audit.reset_completed_at</code>.
     */
    public IndividualPasswordResetAuditRecord setResetCompletedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_password_reset_audit.reset_completed_at</code>.
     */
    public LocalDateTime getResetCompletedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>individual_password_reset_audit.reset_status</code>.
     */
    public IndividualPasswordResetAuditRecord setResetStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.reset_status</code>.
     */
    public String getResetStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>individual_password_reset_audit.is_active</code>.
     */
    public IndividualPasswordResetAuditRecord setIsActive(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>individual_password_reset_audit.created_by</code>.
     */
    public IndividualPasswordResetAuditRecord setCreatedBy(UUID value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>individual_password_reset_audit.updated_by</code>.
     */
    public IndividualPasswordResetAuditRecord setUpdatedBy(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>individual_password_reset_audit.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualPasswordResetAuditRecord
     */
    public IndividualPasswordResetAuditRecord() {
        super(IndividualPasswordResetAudit.INDIVIDUAL_PASSWORD_RESET_AUDIT);
    }

    /**
     * Create a detached, initialised IndividualPasswordResetAuditRecord
     */
    public IndividualPasswordResetAuditRecord(UUID id, UUID individualId, String email, String resetLink, LocalDateTime resetLinkRequestedAt, LocalDateTime resetLinkExpiresAt, LocalDateTime resetCompletedAt, String resetStatus, Boolean isActive, UUID createdBy, UUID updatedBy) {
        super(IndividualPasswordResetAudit.INDIVIDUAL_PASSWORD_RESET_AUDIT);

        setId(id);
        setIndividualId(individualId);
        setEmail(email);
        setResetLink(resetLink);
        setResetLinkRequestedAt(resetLinkRequestedAt);
        setResetLinkExpiresAt(resetLinkExpiresAt);
        setResetCompletedAt(resetCompletedAt);
        setResetStatus(resetStatus);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualPasswordResetAuditRecord
     */
    public IndividualPasswordResetAuditRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.IndividualPasswordResetAudit value) {
        super(IndividualPasswordResetAudit.INDIVIDUAL_PASSWORD_RESET_AUDIT);

        if (value != null) {
            setId(value.getId());
            setIndividualId(value.getIndividualId());
            setEmail(value.getEmail());
            setResetLink(value.getResetLink());
            setResetLinkRequestedAt(value.getResetLinkRequestedAt());
            setResetLinkExpiresAt(value.getResetLinkExpiresAt());
            setResetCompletedAt(value.getResetCompletedAt());
            setResetStatus(value.getResetStatus());
            setIsActive(value.getIsActive());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            resetChangedOnNotNull();
        }
    }
}
