/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.IndividualSessions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualSessionsRecord extends UpdatableRecordImpl<IndividualSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual_sessions.id</code>.
     */
    public IndividualSessionsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual_sessions.individual_id</code>.
     */
    public IndividualSessionsRecord setIndividualId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.individual_id</code>.
     */
    public UUID getIndividualId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>individual_sessions.accesstoken</code>.
     */
    public IndividualSessionsRecord setAccesstoken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.accesstoken</code>.
     */
    public String getAccesstoken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>individual_sessions.accesstoken_expirytime</code>.
     */
    public IndividualSessionsRecord setAccesstokenExpirytime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.accesstoken_expirytime</code>.
     */
    public LocalDateTime getAccesstokenExpirytime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>individual_sessions.accesstoken_generated_on</code>.
     */
    public IndividualSessionsRecord setAccesstokenGeneratedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.accesstoken_generated_on</code>.
     */
    public LocalDateTime getAccesstokenGeneratedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>individual_sessions.refreshtoken</code>.
     */
    public IndividualSessionsRecord setRefreshtoken(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.refreshtoken</code>.
     */
    public String getRefreshtoken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>individual_sessions.refreshtoken_expirytime</code>.
     */
    public IndividualSessionsRecord setRefreshtokenExpirytime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.refreshtoken_expirytime</code>.
     */
    public LocalDateTime getRefreshtokenExpirytime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>individual_sessions.refreshtoken_generated_on</code>.
     */
    public IndividualSessionsRecord setRefreshtokenGeneratedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.refreshtoken_generated_on</code>.
     */
    public LocalDateTime getRefreshtokenGeneratedOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>individual_sessions.ipaddress</code>.
     */
    public IndividualSessionsRecord setIpaddress(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>individual_sessions.ipaddress</code>.
     */
    public String getIpaddress() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualSessionsRecord
     */
    public IndividualSessionsRecord() {
        super(IndividualSessions.INDIVIDUAL_SESSIONS);
    }

    /**
     * Create a detached, initialised IndividualSessionsRecord
     */
    public IndividualSessionsRecord(UUID id, UUID individualId, String accesstoken, LocalDateTime accesstokenExpirytime, LocalDateTime accesstokenGeneratedOn, String refreshtoken, LocalDateTime refreshtokenExpirytime, LocalDateTime refreshtokenGeneratedOn, String ipaddress) {
        super(IndividualSessions.INDIVIDUAL_SESSIONS);

        setId(id);
        setIndividualId(individualId);
        setAccesstoken(accesstoken);
        setAccesstokenExpirytime(accesstokenExpirytime);
        setAccesstokenGeneratedOn(accesstokenGeneratedOn);
        setRefreshtoken(refreshtoken);
        setRefreshtokenExpirytime(refreshtokenExpirytime);
        setRefreshtokenGeneratedOn(refreshtokenGeneratedOn);
        setIpaddress(ipaddress);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualSessionsRecord
     */
    public IndividualSessionsRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.IndividualSessions value) {
        super(IndividualSessions.INDIVIDUAL_SESSIONS);

        if (value != null) {
            setId(value.getId());
            setIndividualId(value.getIndividualId());
            setAccesstoken(value.getAccesstoken());
            setAccesstokenExpirytime(value.getAccesstokenExpirytime());
            setAccesstokenGeneratedOn(value.getAccesstokenGeneratedOn());
            setRefreshtoken(value.getRefreshtoken());
            setRefreshtokenExpirytime(value.getRefreshtokenExpirytime());
            setRefreshtokenGeneratedOn(value.getRefreshtokenGeneratedOn());
            setIpaddress(value.getIpaddress());
            resetChangedOnNotNull();
        }
    }
}
