/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.IndividualRole;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualRoleRecord extends UpdatableRecordImpl<IndividualRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual_role.id</code>.
     */
    public IndividualRoleRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual_role.individual_id</code>.
     */
    public IndividualRoleRecord setIndividualId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.individual_id</code>.
     */
    public UUID getIndividualId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>individual_role.role_id</code>.
     */
    public IndividualRoleRecord setRoleId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.role_id</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>individual_role.created_on</code>.
     */
    public IndividualRoleRecord setCreatedOn(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>individual_role.updated_on</code>.
     */
    public IndividualRoleRecord setUpdatedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>individual_role.created_by</code>.
     */
    public IndividualRoleRecord setCreatedBy(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>individual_role.updated_by</code>.
     */
    public IndividualRoleRecord setUpdatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>individual_role.org_id</code>.
     */
    public IndividualRoleRecord setOrgId(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual_role.org_id</code>.
     */
    public UUID getOrgId() {
        return (UUID) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualRoleRecord
     */
    public IndividualRoleRecord() {
        super(IndividualRole.INDIVIDUAL_ROLE);
    }

    /**
     * Create a detached, initialised IndividualRoleRecord
     */
    public IndividualRoleRecord(UUID id, UUID individualId, UUID roleId, LocalDateTime createdOn, LocalDateTime updatedOn, UUID createdBy, UUID updatedBy, UUID orgId) {
        super(IndividualRole.INDIVIDUAL_ROLE);

        setId(id);
        setIndividualId(individualId);
        setRoleId(roleId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setOrgId(orgId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualRoleRecord
     */
    public IndividualRoleRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.IndividualRole value) {
        super(IndividualRole.INDIVIDUAL_ROLE);

        if (value != null) {
            setId(value.getId());
            setIndividualId(value.getIndividualId());
            setRoleId(value.getRoleId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setOrgId(value.getOrgId());
            resetChangedOnNotNull();
        }
    }
}
