/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.IndividualVerificationAudit;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualVerificationAuditRecord extends UpdatableRecordImpl<IndividualVerificationAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual_verification_audit.id</code>.
     */
    public IndividualVerificationAuditRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual_verification_audit.contact_type</code>.
     */
    public IndividualVerificationAuditRecord setContactType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.contact_type</code>.
     */
    public String getContactType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>individual_verification_audit.contact_value</code>.
     */
    public IndividualVerificationAuditRecord setContactValue(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.contact_value</code>.
     */
    public String getContactValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>individual_verification_audit.activation_link</code>.
     */
    public IndividualVerificationAuditRecord setActivationLink(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.activation_link</code>.
     */
    public Boolean getActivationLink() {
        return (Boolean) get(3);
    }

    /**
     * Setter for
     * <code>individual_verification_audit.activation_link_created_at</code>.
     */
    public IndividualVerificationAuditRecord setActivationLinkCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_verification_audit.activation_link_created_at</code>.
     */
    public LocalDateTime getActivationLinkCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for
     * <code>individual_verification_audit.activation_link_expires_at</code>.
     */
    public IndividualVerificationAuditRecord setActivationLinkExpiresAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_verification_audit.activation_link_expires_at</code>.
     */
    public LocalDateTime getActivationLinkExpiresAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for
     * <code>individual_verification_audit.activation_link_verified_at</code>.
     */
    public IndividualVerificationAuditRecord setActivationLinkVerifiedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_verification_audit.activation_link_verified_at</code>.
     */
    public LocalDateTime getActivationLinkVerifiedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>individual_verification_audit.ip_address</code>.
     */
    public IndividualVerificationAuditRecord setIpAddress(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>individual_verification_audit.role</code>.
     */
    public IndividualVerificationAuditRecord setRole(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.role</code>.
     */
    public String getRole() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>individual_verification_audit.verification_status</code>.
     */
    public IndividualVerificationAuditRecord setVerificationStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>individual_verification_audit.verification_status</code>.
     */
    public String getVerificationStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>individual_verification_audit.is_active</code>.
     */
    public IndividualVerificationAuditRecord setIsActive(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>individual_verification_audit.created_by</code>.
     */
    public IndividualVerificationAuditRecord setCreatedBy(UUID value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>individual_verification_audit.updated_by</code>.
     */
    public IndividualVerificationAuditRecord setUpdatedBy(UUID value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>individual_verification_audit.created_on</code>.
     */
    public IndividualVerificationAuditRecord setCreatedOn(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>individual_verification_audit.updated_on</code>.
     */
    public IndividualVerificationAuditRecord setUpdatedOn(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>individual_verification_audit.otp</code>.
     */
    public IndividualVerificationAuditRecord setOtp(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.otp</code>.
     */
    public String getOtp() {
        return (String) get(15);
    }

    /**
     * Setter for <code>individual_verification_audit.meta_data</code>.
     */
    public IndividualVerificationAuditRecord setMetaData(Map<String, Object> value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.meta_data</code>.
     */
    public Map<String, Object> getMetaData() {
        return (Map<String, Object>) get(16);
    }

    /**
     * Setter for <code>individual_verification_audit.org_id</code>.
     */
    public IndividualVerificationAuditRecord setOrgId(UUID value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>individual_verification_audit.org_id</code>.
     */
    public UUID getOrgId() {
        return (UUID) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualVerificationAuditRecord
     */
    public IndividualVerificationAuditRecord() {
        super(IndividualVerificationAudit.INDIVIDUAL_VERIFICATION_AUDIT);
    }

    /**
     * Create a detached, initialised IndividualVerificationAuditRecord
     */
    public IndividualVerificationAuditRecord(UUID id, String contactType, String contactValue, Boolean activationLink, LocalDateTime activationLinkCreatedAt, LocalDateTime activationLinkExpiresAt, LocalDateTime activationLinkVerifiedAt, String ipAddress, String role, String verificationStatus, Boolean isActive, UUID createdBy, UUID updatedBy, LocalDateTime createdOn, LocalDateTime updatedOn, String otp, Map<String, Object> metaData, UUID orgId) {
        super(IndividualVerificationAudit.INDIVIDUAL_VERIFICATION_AUDIT);

        setId(id);
        setContactType(contactType);
        setContactValue(contactValue);
        setActivationLink(activationLink);
        setActivationLinkCreatedAt(activationLinkCreatedAt);
        setActivationLinkExpiresAt(activationLinkExpiresAt);
        setActivationLinkVerifiedAt(activationLinkVerifiedAt);
        setIpAddress(ipAddress);
        setRole(role);
        setVerificationStatus(verificationStatus);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setOtp(otp);
        setMetaData(metaData);
        setOrgId(orgId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualVerificationAuditRecord
     */
    public IndividualVerificationAuditRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.IndividualVerificationAudit value) {
        super(IndividualVerificationAudit.INDIVIDUAL_VERIFICATION_AUDIT);

        if (value != null) {
            setId(value.getId());
            setContactType(value.getContactType());
            setContactValue(value.getContactValue());
            setActivationLink(value.getActivationLink());
            setActivationLinkCreatedAt(value.getActivationLinkCreatedAt());
            setActivationLinkExpiresAt(value.getActivationLinkExpiresAt());
            setActivationLinkVerifiedAt(value.getActivationLinkVerifiedAt());
            setIpAddress(value.getIpAddress());
            setRole(value.getRole());
            setVerificationStatus(value.getVerificationStatus());
            setIsActive(value.getIsActive());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setOtp(value.getOtp());
            setMetaData(value.getMetaData());
            setOrgId(value.getOrgId());
            resetChangedOnNotNull();
        }
    }
}
