/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPermission;
import com.ganithyanthram.modularapp.entitlement.common.dto.RoleNode;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualPermissionRecord extends UpdatableRecordImpl<IndividualPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual_permission.id</code>.
     */
    public IndividualPermissionRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual_permission.individual_id</code>.
     */
    public IndividualPermissionRecord setIndividualId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.individual_id</code>.
     */
    public UUID getIndividualId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>individual_permission.permissions</code>.
     */
    public IndividualPermissionRecord setPermissions(List<RoleNode> value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.permissions</code>.
     */
    public List<RoleNode> getPermissions() {
        return (List<RoleNode>) get(2);
    }

    /**
     * Setter for <code>individual_permission.created_on</code>.
     */
    public IndividualPermissionRecord setCreatedOn(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>individual_permission.created_by</code>.
     */
    public IndividualPermissionRecord setCreatedBy(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>individual_permission.updated_on</code>.
     */
    public IndividualPermissionRecord setUpdatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>individual_permission.updated_by</code>.
     */
    public IndividualPermissionRecord setUpdatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>individual_permission.remarks</code>.
     */
    public IndividualPermissionRecord setRemarks(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(7);
    }

    /**
     * Setter for <code>individual_permission.org_id</code>.
     */
    public IndividualPermissionRecord setOrgId(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.org_id</code>.
     */
    public UUID getOrgId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>individual_permission.pages</code>.
     */
    public IndividualPermissionRecord setPages(List<RoleNode> value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>individual_permission.pages</code>.
     */
    public List<RoleNode> getPages() {
        return (List<RoleNode>) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualPermissionRecord
     */
    public IndividualPermissionRecord() {
        super(IndividualPermission.INDIVIDUAL_PERMISSION);
    }

    /**
     * Create a detached, initialised IndividualPermissionRecord
     */
    public IndividualPermissionRecord(UUID id, UUID individualId, List<RoleNode> permissions, LocalDateTime createdOn, UUID createdBy, LocalDateTime updatedOn, UUID updatedBy, String remarks, UUID orgId, List<RoleNode> pages) {
        super(IndividualPermission.INDIVIDUAL_PERMISSION);

        setId(id);
        setIndividualId(individualId);
        setPermissions(permissions);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        setUpdatedOn(updatedOn);
        setUpdatedBy(updatedBy);
        setRemarks(remarks);
        setOrgId(orgId);
        setPages(pages);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualPermissionRecord
     */
    public IndividualPermissionRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.IndividualPermission value) {
        super(IndividualPermission.INDIVIDUAL_PERMISSION);

        if (value != null) {
            setId(value.getId());
            setIndividualId(value.getIndividualId());
            setPermissions(value.getPermissions());
            setCreatedOn(value.getCreatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedOn(value.getUpdatedOn());
            setUpdatedBy(value.getUpdatedBy());
            setRemarks(value.getRemarks());
            setOrgId(value.getOrgId());
            setPages(value.getPages());
            resetChangedOnNotNull();
        }
    }
}
