/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.Individual;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualRecord extends UpdatableRecordImpl<IndividualRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>individual.id</code>.
     */
    public IndividualRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>individual.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>individual.name</code>.
     */
    public IndividualRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>individual.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>individual.email</code>.
     */
    public IndividualRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>individual.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>individual.mobile_number</code>.
     */
    public IndividualRecord setMobileNumber(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>individual.mobile_number</code>.
     */
    public String getMobileNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>individual.password</code>.
     */
    public IndividualRecord setPassword(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>individual.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>individual.social_login_provider</code>.
     */
    public IndividualRecord setSocialLoginProvider(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>individual.social_login_provider</code>.
     */
    public String getSocialLoginProvider() {
        return (String) get(5);
    }

    /**
     * Setter for <code>individual.social_login_provider_id</code>.
     */
    public IndividualRecord setSocialLoginProviderId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>individual.social_login_provider_id</code>.
     */
    public String getSocialLoginProviderId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>individual.social_login_provider_image_url</code>.
     */
    public IndividualRecord setSocialLoginProviderImageUrl(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>individual.social_login_provider_image_url</code>.
     */
    public String getSocialLoginProviderImageUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>individual.meta_data</code>.
     */
    public IndividualRecord setMetaData(Map<String, Object> value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>individual.meta_data</code>.
     */
    public Map<String, Object> getMetaData() {
        return (Map<String, Object>) get(8);
    }

    /**
     * Setter for <code>individual.is_active</code>.
     */
    public IndividualRecord setIsActive(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>individual.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>individual.created_by</code>.
     */
    public IndividualRecord setCreatedBy(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>individual.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>individual.updated_by</code>.
     */
    public IndividualRecord setUpdatedBy(UUID value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>individual.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>individual.created_on</code>.
     */
    public IndividualRecord setCreatedOn(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>individual.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>individual.updated_on</code>.
     */
    public IndividualRecord setUpdatedOn(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>individual.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndividualRecord
     */
    public IndividualRecord() {
        super(Individual.INDIVIDUAL);
    }

    /**
     * Create a detached, initialised IndividualRecord
     */
    public IndividualRecord(UUID id, String name, String email, String mobileNumber, String password, String socialLoginProvider, String socialLoginProviderId, String socialLoginProviderImageUrl, Map<String, Object> metaData, Boolean isActive, UUID createdBy, UUID updatedBy, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(Individual.INDIVIDUAL);

        setId(id);
        setName(name);
        setEmail(email);
        setMobileNumber(mobileNumber);
        setPassword(password);
        setSocialLoginProvider(socialLoginProvider);
        setSocialLoginProviderId(socialLoginProviderId);
        setSocialLoginProviderImageUrl(socialLoginProviderImageUrl);
        setMetaData(metaData);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised IndividualRecord
     */
    public IndividualRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.Individual value) {
        super(Individual.INDIVIDUAL);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setMobileNumber(value.getMobileNumber());
            setPassword(value.getPassword());
            setSocialLoginProvider(value.getSocialLoginProvider());
            setSocialLoginProviderId(value.getSocialLoginProviderId());
            setSocialLoginProviderImageUrl(value.getSocialLoginProviderImageUrl());
            setMetaData(value.getMetaData());
            setIsActive(value.getIsActive());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetChangedOnNotNull();
        }
    }
}
