/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.ListNames;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListNamesRecord extends UpdatableRecordImpl<ListNamesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>list_names.id</code>.
     */
    public ListNamesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>list_names.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>list_names.name</code>.
     */
    public ListNamesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>list_names.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>list_names.is_active</code>.
     */
    public ListNamesRecord setIsActive(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>list_names.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>list_names.created_by</code>.
     */
    public ListNamesRecord setCreatedBy(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>list_names.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>list_names.updated_by</code>.
     */
    public ListNamesRecord setUpdatedBy(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>list_names.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>list_names.created_on</code>.
     */
    public ListNamesRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>list_names.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>list_names.updated_on</code>.
     */
    public ListNamesRecord setUpdatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>list_names.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>list_names.is_statistics</code>.
     */
    public ListNamesRecord setIsStatistics(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>list_names.is_statistics</code>.
     */
    public Boolean getIsStatistics() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListNamesRecord
     */
    public ListNamesRecord() {
        super(ListNames.LIST_NAMES);
    }

    /**
     * Create a detached, initialised ListNamesRecord
     */
    public ListNamesRecord(UUID id, String name, Boolean isActive, UUID createdBy, UUID updatedBy, LocalDateTime createdOn, LocalDateTime updatedOn, Boolean isStatistics) {
        super(ListNames.LIST_NAMES);

        setId(id);
        setName(name);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setIsStatistics(isStatistics);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ListNamesRecord
     */
    public ListNamesRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.ListNames value) {
        super(ListNames.LIST_NAMES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setIsActive(value.getIsActive());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setIsStatistics(value.getIsStatistics());
            resetChangedOnNotNull();
        }
    }
}
