/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.ListValues;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListValuesRecord extends UpdatableRecordImpl<ListValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>list_values.id</code>.
     */
    public ListValuesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>list_values.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>list_values.name</code>.
     */
    public ListValuesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>list_values.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>list_values.list_names_id</code>.
     */
    public ListValuesRecord setListNamesId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>list_values.list_names_id</code>.
     */
    public UUID getListNamesId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>list_values.is_active</code>.
     */
    public ListValuesRecord setIsActive(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>list_values.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>list_values.created_by</code>.
     */
    public ListValuesRecord setCreatedBy(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>list_values.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>list_values.updated_by</code>.
     */
    public ListValuesRecord setUpdatedBy(UUID value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>list_values.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>list_values.created_on</code>.
     */
    public ListValuesRecord setCreatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>list_values.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>list_values.updated_on</code>.
     */
    public ListValuesRecord setUpdatedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>list_values.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>list_values.code</code>.
     */
    public ListValuesRecord setCode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>list_values.code</code>.
     */
    public String getCode() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListValuesRecord
     */
    public ListValuesRecord() {
        super(ListValues.LIST_VALUES);
    }

    /**
     * Create a detached, initialised ListValuesRecord
     */
    public ListValuesRecord(UUID id, String name, UUID listNamesId, Boolean isActive, UUID createdBy, UUID updatedBy, LocalDateTime createdOn, LocalDateTime updatedOn, String code) {
        super(ListValues.LIST_VALUES);

        setId(id);
        setName(name);
        setListNamesId(listNamesId);
        setIsActive(isActive);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setCode(code);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ListValuesRecord
     */
    public ListValuesRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.ListValues value) {
        super(ListValues.LIST_VALUES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setListNamesId(value.getListNamesId());
            setIsActive(value.getIsActive());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setCode(value.getCode());
            resetChangedOnNotNull();
        }
    }
}
