/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.Organisation;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrganisationRecord extends UpdatableRecordImpl<OrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>organisation.id</code>.
     */
    public OrganisationRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>organisation.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>organisation.name</code>.
     */
    public OrganisationRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>organisation.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>organisation.category</code>.
     */
    public OrganisationRecord setCategory(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>organisation.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>organisation.meta_data</code>.
     */
    public OrganisationRecord setMetaData(Map<String, Object> value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>organisation.meta_data</code>.
     */
    public Map<String, Object> getMetaData() {
        return (Map<String, Object>) get(3);
    }

    /**
     * Setter for <code>organisation.is_active</code>.
     */
    public OrganisationRecord setIsActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>organisation.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>organisation.status</code>.
     */
    public OrganisationRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>organisation.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>organisation.created_by</code>.
     */
    public OrganisationRecord setCreatedBy(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>organisation.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>organisation.updated_by</code>.
     */
    public OrganisationRecord setUpdatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>organisation.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>organisation.created_on</code>.
     */
    public OrganisationRecord setCreatedOn(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>organisation.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>organisation.updated_on</code>.
     */
    public OrganisationRecord setUpdatedOn(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>organisation.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationRecord
     */
    public OrganisationRecord() {
        super(Organisation.ORGANISATION);
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(UUID id, String name, String category, Map<String, Object> metaData, Boolean isActive, String status, UUID createdBy, UUID updatedBy, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(Organisation.ORGANISATION);

        setId(id);
        setName(name);
        setCategory(category);
        setMetaData(metaData);
        setIsActive(isActive);
        setStatus(status);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.Organisation value) {
        super(Organisation.ORGANISATION);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCategory(value.getCategory());
            setMetaData(value.getMetaData());
            setIsActive(value.getIsActive());
            setStatus(value.getStatus());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            resetChangedOnNotNull();
        }
    }
}
