/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.Roles;
import com.ganithyanthram.modularapp.entitlement.common.dto.RoleNode;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>roles.id</code>.
     */
    public RolesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>roles.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>roles.name</code>.
     */
    public RolesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>roles.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>roles.description</code>.
     */
    public RolesRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>roles.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>roles.parent_role_id</code>.
     */
    public RolesRecord setParentRoleId(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>roles.parent_role_id</code>.
     */
    public UUID getParentRoleId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>roles.is_active</code>.
     */
    public RolesRecord setIsActive(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>roles.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>roles.created_on</code>.
     */
    public RolesRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>roles.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>roles.updated_on</code>.
     */
    public RolesRecord setUpdatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>roles.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>roles.created_by</code>.
     */
    public RolesRecord setCreatedBy(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>roles.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>roles.updated_by</code>.
     */
    public RolesRecord setUpdatedBy(UUID value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>roles.updated_by</code>.
     */
    public UUID getUpdatedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>roles.permissions</code>.
     */
    public RolesRecord setPermissions(List<RoleNode> value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>roles.permissions</code>.
     */
    public List<RoleNode> getPermissions() {
        return (List<RoleNode>) get(9);
    }

    /**
     * Setter for <code>roles.org_id</code>.
     */
    public RolesRecord setOrgId(UUID value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>roles.org_id</code>.
     */
    public UUID getOrgId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>roles.pages</code>.
     */
    public RolesRecord setPages(List<RoleNode> value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>roles.pages</code>.
     */
    public List<RoleNode> getPages() {
        return (List<RoleNode>) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(UUID id, String name, String description, UUID parentRoleId, Boolean isActive, LocalDateTime createdOn, LocalDateTime updatedOn, UUID createdBy, UUID updatedBy, List<RoleNode> permissions, UUID orgId, List<RoleNode> pages) {
        super(Roles.ROLES);

        setId(id);
        setName(name);
        setDescription(description);
        setParentRoleId(parentRoleId);
        setIsActive(isActive);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setPermissions(permissions);
        setOrgId(orgId);
        setPages(pages);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.Roles value) {
        super(Roles.ROLES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setParentRoleId(value.getParentRoleId());
            setIsActive(value.getIsActive());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setPermissions(value.getPermissions());
            setOrgId(value.getOrgId());
            setPages(value.getPages());
            resetChangedOnNotNull();
        }
    }
}
