/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.records;


import com.ganithyanthram.modularapp.db.jooq.tables.UserProfiles;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfilesRecord extends UpdatableRecordImpl<UserProfilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_profiles.id</code>.
     */
    public UserProfilesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>user_profiles.user_id</code>.
     */
    public UserProfilesRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>user_profiles.bio</code>.
     */
    public UserProfilesRecord setBio(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.bio</code>.
     */
    public String getBio() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_profiles.avatar_url</code>.
     */
    public UserProfilesRecord setAvatarUrl(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.avatar_url</code>.
     */
    public String getAvatarUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_profiles.phone_number</code>.
     */
    public UserProfilesRecord setPhoneNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_profiles.date_of_birth</code>.
     */
    public UserProfilesRecord setDateOfBirth(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>user_profiles.metadata</code>.
     */
    public UserProfilesRecord setMetadata(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>user_profiles.created_at</code>.
     */
    public UserProfilesRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>user_profiles.updated_at</code>.
     */
    public UserProfilesRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>user_profiles.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfilesRecord
     */
    public UserProfilesRecord() {
        super(UserProfiles.USER_PROFILES);
    }

    /**
     * Create a detached, initialised UserProfilesRecord
     */
    public UserProfilesRecord(UUID id, UUID userId, String bio, String avatarUrl, String phoneNumber, LocalDate dateOfBirth, JSONB metadata, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(UserProfiles.USER_PROFILES);

        setId(id);
        setUserId(userId);
        setBio(bio);
        setAvatarUrl(avatarUrl);
        setPhoneNumber(phoneNumber);
        setDateOfBirth(dateOfBirth);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserProfilesRecord
     */
    public UserProfilesRecord(com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles value) {
        super(UserProfiles.USER_PROFILES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setBio(value.getBio());
            setAvatarUrl(value.getAvatarUrl());
            setPhoneNumber(value.getPhoneNumber());
            setDateOfBirth(value.getDateOfBirth());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
