/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID userId;
    private String bio;
    private String avatarUrl;
    private String phoneNumber;
    private LocalDate dateOfBirth;
    private JSONB metadata;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public UserProfiles() {}

    public UserProfiles(UserProfiles value) {
        this.id = value.id;
        this.userId = value.userId;
        this.bio = value.bio;
        this.avatarUrl = value.avatarUrl;
        this.phoneNumber = value.phoneNumber;
        this.dateOfBirth = value.dateOfBirth;
        this.metadata = value.metadata;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public UserProfiles(
        UUID id,
        UUID userId,
        String bio,
        String avatarUrl,
        String phoneNumber,
        LocalDate dateOfBirth,
        JSONB metadata,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.bio = bio;
        this.avatarUrl = avatarUrl;
        this.phoneNumber = phoneNumber;
        this.dateOfBirth = dateOfBirth;
        this.metadata = metadata;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>user_profiles.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>user_profiles.id</code>.
     */
    public UserProfiles setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>user_profiles.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>user_profiles.user_id</code>.
     */
    public UserProfiles setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>user_profiles.bio</code>.
     */
    public String getBio() {
        return this.bio;
    }

    /**
     * Setter for <code>user_profiles.bio</code>.
     */
    public UserProfiles setBio(String bio) {
        this.bio = bio;
        return this;
    }

    /**
     * Getter for <code>user_profiles.avatar_url</code>.
     */
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    /**
     * Setter for <code>user_profiles.avatar_url</code>.
     */
    public UserProfiles setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
        return this;
    }

    /**
     * Getter for <code>user_profiles.phone_number</code>.
     */
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>user_profiles.phone_number</code>.
     */
    public UserProfiles setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    /**
     * Getter for <code>user_profiles.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    /**
     * Setter for <code>user_profiles.date_of_birth</code>.
     */
    public UserProfiles setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * Getter for <code>user_profiles.metadata</code>.
     */
    public JSONB getMetadata() {
        return this.metadata;
    }

    /**
     * Setter for <code>user_profiles.metadata</code>.
     */
    public UserProfiles setMetadata(JSONB metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Getter for <code>user_profiles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>user_profiles.created_at</code>.
     */
    public UserProfiles setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>user_profiles.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>user_profiles.updated_at</code>.
     */
    public UserProfiles setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserProfiles other = (UserProfiles) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.bio == null) {
            if (other.bio != null)
                return false;
        }
        else if (!this.bio.equals(other.bio))
            return false;
        if (this.avatarUrl == null) {
            if (other.avatarUrl != null)
                return false;
        }
        else if (!this.avatarUrl.equals(other.avatarUrl))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.dateOfBirth == null) {
            if (other.dateOfBirth != null)
                return false;
        }
        else if (!this.dateOfBirth.equals(other.dateOfBirth))
            return false;
        if (this.metadata == null) {
            if (other.metadata != null)
                return false;
        }
        else if (!this.metadata.equals(other.metadata))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.bio == null) ? 0 : this.bio.hashCode());
        result = prime * result + ((this.avatarUrl == null) ? 0 : this.avatarUrl.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.dateOfBirth == null) ? 0 : this.dateOfBirth.hashCode());
        result = prime * result + ((this.metadata == null) ? 0 : this.metadata.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserProfiles (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(bio);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(metadata);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
