spring.application.name=modular-app

spring.datasource.url=jdbc:postgresql://192.168.64.8:5432/modularapp
spring.datasource.username=modularapp
spring.datasource.password=modularapp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=POSTGRES
spring.jooq.execute-batch=true
spring.jooq.execute-batch-size=1000
spring.jooq.execute-batch-timeout=10000
spring.jooq.execute-batch-timeout-unit=MILLISECONDS

spring.datasource.hikari.pool-name=ModularAppDataSource
spring.datasource.hikari.pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-timeout-unit=MILLISECONDS