/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPasswordResetAudit.IndividualPasswordResetAuditPath;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPermission.IndividualPermissionPath;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualRole.IndividualRolePath;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualSessions.IndividualSessionsPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualRecord;
import com.ganithyanthram.modularapp.entitlement.common.converter.JsonbConverter;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Individual extends TableImpl<IndividualRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual</code>
     */
    public static final Individual INDIVIDUAL = new Individual();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualRecord> getRecordType() {
        return IndividualRecord.class;
    }

    /**
     * The column <code>individual.id</code>.
     */
    public final TableField<IndividualRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual.name</code>.
     */
    public final TableField<IndividualRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>individual.email</code>.
     */
    public final TableField<IndividualRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>individual.mobile_number</code>.
     */
    public final TableField<IndividualRecord, String> MOBILE_NUMBER = createField(DSL.name("mobile_number"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>individual.password</code>.
     */
    public final TableField<IndividualRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>individual.social_login_provider</code>.
     */
    public final TableField<IndividualRecord, String> SOCIAL_LOGIN_PROVIDER = createField(DSL.name("social_login_provider"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>individual.social_login_provider_id</code>.
     */
    public final TableField<IndividualRecord, String> SOCIAL_LOGIN_PROVIDER_ID = createField(DSL.name("social_login_provider_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>individual.social_login_provider_image_url</code>.
     */
    public final TableField<IndividualRecord, String> SOCIAL_LOGIN_PROVIDER_IMAGE_URL = createField(DSL.name("social_login_provider_image_url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>individual.meta_data</code>.
     */
    public final TableField<IndividualRecord, Map<String, Object>> META_DATA = createField(DSL.name("meta_data"), SQLDataType.JSONB, this, "", new JsonbConverter());

    /**
     * The column <code>individual.is_active</code>.
     */
    public final TableField<IndividualRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>individual.created_by</code>.
     */
    public final TableField<IndividualRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual.updated_by</code>.
     */
    public final TableField<IndividualRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual.created_on</code>.
     */
    public final TableField<IndividualRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>individual.updated_on</code>.
     */
    public final TableField<IndividualRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Individual(Name alias, Table<IndividualRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Individual(Name alias, Table<IndividualRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual</code> table reference
     */
    public Individual(String alias) {
        this(DSL.name(alias), INDIVIDUAL);
    }

    /**
     * Create an aliased <code>individual</code> table reference
     */
    public Individual(Name alias) {
        this(alias, INDIVIDUAL);
    }

    /**
     * Create a <code>individual</code> table reference
     */
    public Individual() {
        this(DSL.name("individual"), null);
    }

    public <O extends Record> Individual(Table<O> path, ForeignKey<O, IndividualRecord> childPath, InverseForeignKey<O, IndividualRecord> parentPath) {
        super(path, childPath, parentPath, INDIVIDUAL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndividualPath extends Individual implements Path<IndividualRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IndividualPath(Table<O> path, ForeignKey<O, IndividualRecord> childPath, InverseForeignKey<O, IndividualRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndividualPath(Name alias, Table<IndividualRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndividualPath as(String alias) {
            return new IndividualPath(DSL.name(alias), this);
        }

        @Override
        public IndividualPath as(Name alias) {
            return new IndividualPath(alias, this);
        }

        @Override
        public IndividualPath as(Table<?> alias) {
            return new IndividualPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_INDIVIDUAL_EMAIL, Indexes.IDX_INDIVIDUAL_IS_ACTIVE);
    }

    @Override
    public UniqueKey<IndividualRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_PKEY;
    }

    @Override
    public List<UniqueKey<IndividualRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.INDIVIDUAL_EMAIL_UNIQUE);
    }

    private transient IndividualPasswordResetAuditPath _individualPasswordResetAudit;

    /**
     * Get the implicit to-many join path to the
     * <code>individual_password_reset_audit</code> table
     */
    public IndividualPasswordResetAuditPath individualPasswordResetAudit() {
        if (_individualPasswordResetAudit == null)
            _individualPasswordResetAudit = new IndividualPasswordResetAuditPath(this, null, Keys.INDIVIDUAL_PASSWORD_RESET_AUDIT__INDIVIDUAL_PASSWORD_RESET_AUDIT_INDIVIDUAL_ID_FKEY.getInverseKey());

        return _individualPasswordResetAudit;
    }

    private transient IndividualPermissionPath _individualPermission;

    /**
     * Get the implicit to-many join path to the
     * <code>individual_permission</code> table
     */
    public IndividualPermissionPath individualPermission() {
        if (_individualPermission == null)
            _individualPermission = new IndividualPermissionPath(this, null, Keys.INDIVIDUAL_PERMISSION__INDIVIDUAL_PERMISSION_INDIVIDUAL_FK.getInverseKey());

        return _individualPermission;
    }

    private transient IndividualRolePath _individualRole;

    /**
     * Get the implicit to-many join path to the <code>individual_role</code>
     * table
     */
    public IndividualRolePath individualRole() {
        if (_individualRole == null)
            _individualRole = new IndividualRolePath(this, null, Keys.INDIVIDUAL_ROLE__INDIVIDUAL_ROLE_INDIVIDUAL_ID_FK.getInverseKey());

        return _individualRole;
    }

    private transient IndividualSessionsPath _individualSessions;

    /**
     * Get the implicit to-many join path to the
     * <code>individual_sessions</code> table
     */
    public IndividualSessionsPath individualSessions() {
        if (_individualSessions == null)
            _individualSessions = new IndividualSessionsPath(this, null, Keys.INDIVIDUAL_SESSIONS__INDIVIDUAL_SESSIONS_IND_FK.getInverseKey());

        return _individualSessions;
    }

    @Override
    public Individual as(String alias) {
        return new Individual(DSL.name(alias), this);
    }

    @Override
    public Individual as(Name alias) {
        return new Individual(alias, this);
    }

    @Override
    public Individual as(Table<?> alias) {
        return new Individual(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Individual rename(String name) {
        return new Individual(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Individual rename(Name name) {
        return new Individual(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Individual rename(Table<?> name) {
        return new Individual(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual where(Condition condition) {
        return new Individual(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Individual where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Individual where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Individual where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Individual where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Individual whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
