/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualVerificationAuditRecord;
import com.ganithyanthram.modularapp.entitlement.common.converter.JsonbConverter;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualVerificationAudit extends TableImpl<IndividualVerificationAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual_verification_audit</code>
     */
    public static final IndividualVerificationAudit INDIVIDUAL_VERIFICATION_AUDIT = new IndividualVerificationAudit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualVerificationAuditRecord> getRecordType() {
        return IndividualVerificationAuditRecord.class;
    }

    /**
     * The column <code>individual_verification_audit.id</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_verification_audit.contact_type</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> CONTACT_TYPE = createField(DSL.name("contact_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>individual_verification_audit.contact_value</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> CONTACT_VALUE = createField(DSL.name("contact_value"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>individual_verification_audit.activation_link</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, Boolean> ACTIVATION_LINK = createField(DSL.name("activation_link"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column
     * <code>individual_verification_audit.activation_link_created_at</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, LocalDateTime> ACTIVATION_LINK_CREATED_AT = createField(DSL.name("activation_link_created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>individual_verification_audit.activation_link_expires_at</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, LocalDateTime> ACTIVATION_LINK_EXPIRES_AT = createField(DSL.name("activation_link_expires_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>individual_verification_audit.activation_link_verified_at</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, LocalDateTime> ACTIVATION_LINK_VERIFIED_AT = createField(DSL.name("activation_link_verified_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>individual_verification_audit.ip_address</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>individual_verification_audit.role</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column
     * <code>individual_verification_audit.verification_status</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> VERIFICATION_STATUS = createField(DSL.name("verification_status"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>individual_verification_audit.is_active</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>individual_verification_audit.created_by</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_verification_audit.updated_by</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_verification_audit.created_on</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>individual_verification_audit.updated_on</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>individual_verification_audit.otp</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, String> OTP = createField(DSL.name("otp"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>individual_verification_audit.meta_data</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, Map<String, Object>> META_DATA = createField(DSL.name("meta_data"), SQLDataType.JSONB, this, "", new JsonbConverter());

    /**
     * The column <code>individual_verification_audit.org_id</code>.
     */
    public final TableField<IndividualVerificationAuditRecord, UUID> ORG_ID = createField(DSL.name("org_id"), SQLDataType.UUID, this, "");

    private IndividualVerificationAudit(Name alias, Table<IndividualVerificationAuditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndividualVerificationAudit(Name alias, Table<IndividualVerificationAuditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual_verification_audit</code> table
     * reference
     */
    public IndividualVerificationAudit(String alias) {
        this(DSL.name(alias), INDIVIDUAL_VERIFICATION_AUDIT);
    }

    /**
     * Create an aliased <code>individual_verification_audit</code> table
     * reference
     */
    public IndividualVerificationAudit(Name alias) {
        this(alias, INDIVIDUAL_VERIFICATION_AUDIT);
    }

    /**
     * Create a <code>individual_verification_audit</code> table reference
     */
    public IndividualVerificationAudit() {
        this(DSL.name("individual_verification_audit"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_VERIFICATION_CONTACT_VALUE, Indexes.IDX_VERIFICATION_STATUS);
    }

    @Override
    public UniqueKey<IndividualVerificationAuditRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_VERIFICATION_AUDIT_PKEY;
    }

    @Override
    public IndividualVerificationAudit as(String alias) {
        return new IndividualVerificationAudit(DSL.name(alias), this);
    }

    @Override
    public IndividualVerificationAudit as(Name alias) {
        return new IndividualVerificationAudit(alias, this);
    }

    @Override
    public IndividualVerificationAudit as(Table<?> alias) {
        return new IndividualVerificationAudit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualVerificationAudit rename(String name) {
        return new IndividualVerificationAudit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualVerificationAudit rename(Name name) {
        return new IndividualVerificationAudit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualVerificationAudit rename(Table<?> name) {
        return new IndividualVerificationAudit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit where(Condition condition) {
        return new IndividualVerificationAudit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualVerificationAudit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualVerificationAudit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualVerificationAudit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualVerificationAudit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualVerificationAudit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
