/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Individual.IndividualPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualPermissionRecord;
import com.ganithyanthram.modularapp.entitlement.common.converter.RoleNodeListConverter;
import com.ganithyanthram.modularapp.entitlement.common.dto.RoleNode;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualPermission extends TableImpl<IndividualPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual_permission</code>
     */
    public static final IndividualPermission INDIVIDUAL_PERMISSION = new IndividualPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualPermissionRecord> getRecordType() {
        return IndividualPermissionRecord.class;
    }

    /**
     * The column <code>individual_permission.id</code>.
     */
    public final TableField<IndividualPermissionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_permission.individual_id</code>.
     */
    public final TableField<IndividualPermissionRecord, UUID> INDIVIDUAL_ID = createField(DSL.name("individual_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_permission.permissions</code>.
     */
    public final TableField<IndividualPermissionRecord, List<RoleNode>> PERMISSIONS = createField(DSL.name("permissions"), SQLDataType.JSONB.nullable(false), this, "", new RoleNodeListConverter());

    /**
     * The column <code>individual_permission.created_on</code>.
     */
    public final TableField<IndividualPermissionRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>individual_permission.created_by</code>.
     */
    public final TableField<IndividualPermissionRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_permission.updated_on</code>.
     */
    public final TableField<IndividualPermissionRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>individual_permission.updated_by</code>.
     */
    public final TableField<IndividualPermissionRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_permission.remarks</code>.
     */
    public final TableField<IndividualPermissionRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>individual_permission.org_id</code>.
     */
    public final TableField<IndividualPermissionRecord, UUID> ORG_ID = createField(DSL.name("org_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_permission.pages</code>.
     */
    public final TableField<IndividualPermissionRecord, List<RoleNode>> PAGES = createField(DSL.name("pages"), SQLDataType.JSONB, this, "", new RoleNodeListConverter());

    private IndividualPermission(Name alias, Table<IndividualPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndividualPermission(Name alias, Table<IndividualPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual_permission</code> table reference
     */
    public IndividualPermission(String alias) {
        this(DSL.name(alias), INDIVIDUAL_PERMISSION);
    }

    /**
     * Create an aliased <code>individual_permission</code> table reference
     */
    public IndividualPermission(Name alias) {
        this(alias, INDIVIDUAL_PERMISSION);
    }

    /**
     * Create a <code>individual_permission</code> table reference
     */
    public IndividualPermission() {
        this(DSL.name("individual_permission"), null);
    }

    public <O extends Record> IndividualPermission(Table<O> path, ForeignKey<O, IndividualPermissionRecord> childPath, InverseForeignKey<O, IndividualPermissionRecord> parentPath) {
        super(path, childPath, parentPath, INDIVIDUAL_PERMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndividualPermissionPath extends IndividualPermission implements Path<IndividualPermissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IndividualPermissionPath(Table<O> path, ForeignKey<O, IndividualPermissionRecord> childPath, InverseForeignKey<O, IndividualPermissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndividualPermissionPath(Name alias, Table<IndividualPermissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndividualPermissionPath as(String alias) {
            return new IndividualPermissionPath(DSL.name(alias), this);
        }

        @Override
        public IndividualPermissionPath as(Name alias) {
            return new IndividualPermissionPath(alias, this);
        }

        @Override
        public IndividualPermissionPath as(Table<?> alias) {
            return new IndividualPermissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_INDIVIDUAL_PERMISSION_INDIVIDUAL_ID, Indexes.IDX_INDIVIDUAL_PERMISSION_ORG_ID);
    }

    @Override
    public UniqueKey<IndividualPermissionRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_PERMISSION_PK;
    }

    @Override
    public List<ForeignKey<IndividualPermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDIVIDUAL_PERMISSION__INDIVIDUAL_PERMISSION_INDIVIDUAL_FK);
    }

    private transient IndividualPath _individual;

    /**
     * Get the implicit join path to the <code>individual</code> table.
     */
    public IndividualPath individual() {
        if (_individual == null)
            _individual = new IndividualPath(this, Keys.INDIVIDUAL_PERMISSION__INDIVIDUAL_PERMISSION_INDIVIDUAL_FK, null);

        return _individual;
    }

    @Override
    public IndividualPermission as(String alias) {
        return new IndividualPermission(DSL.name(alias), this);
    }

    @Override
    public IndividualPermission as(Name alias) {
        return new IndividualPermission(alias, this);
    }

    @Override
    public IndividualPermission as(Table<?> alias) {
        return new IndividualPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPermission rename(String name) {
        return new IndividualPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPermission rename(Name name) {
        return new IndividualPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPermission rename(Table<?> name) {
        return new IndividualPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission where(Condition condition) {
        return new IndividualPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
