/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Individual.IndividualPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualPasswordResetAuditRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualPasswordResetAudit extends TableImpl<IndividualPasswordResetAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual_password_reset_audit</code>
     */
    public static final IndividualPasswordResetAudit INDIVIDUAL_PASSWORD_RESET_AUDIT = new IndividualPasswordResetAudit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualPasswordResetAuditRecord> getRecordType() {
        return IndividualPasswordResetAuditRecord.class;
    }

    /**
     * The column <code>individual_password_reset_audit.id</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_password_reset_audit.individual_id</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, UUID> INDIVIDUAL_ID = createField(DSL.name("individual_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_password_reset_audit.email</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>individual_password_reset_audit.reset_link</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, String> RESET_LINK = createField(DSL.name("reset_link"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column
     * <code>individual_password_reset_audit.reset_link_requested_at</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, LocalDateTime> RESET_LINK_REQUESTED_AT = createField(DSL.name("reset_link_requested_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>individual_password_reset_audit.reset_link_expires_at</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, LocalDateTime> RESET_LINK_EXPIRES_AT = createField(DSL.name("reset_link_expires_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>individual_password_reset_audit.reset_completed_at</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, LocalDateTime> RESET_COMPLETED_AT = createField(DSL.name("reset_completed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>individual_password_reset_audit.reset_status</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, String> RESET_STATUS = createField(DSL.name("reset_status"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>individual_password_reset_audit.is_active</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>individual_password_reset_audit.created_by</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_password_reset_audit.updated_by</code>.
     */
    public final TableField<IndividualPasswordResetAuditRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    private IndividualPasswordResetAudit(Name alias, Table<IndividualPasswordResetAuditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndividualPasswordResetAudit(Name alias, Table<IndividualPasswordResetAuditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual_password_reset_audit</code> table
     * reference
     */
    public IndividualPasswordResetAudit(String alias) {
        this(DSL.name(alias), INDIVIDUAL_PASSWORD_RESET_AUDIT);
    }

    /**
     * Create an aliased <code>individual_password_reset_audit</code> table
     * reference
     */
    public IndividualPasswordResetAudit(Name alias) {
        this(alias, INDIVIDUAL_PASSWORD_RESET_AUDIT);
    }

    /**
     * Create a <code>individual_password_reset_audit</code> table reference
     */
    public IndividualPasswordResetAudit() {
        this(DSL.name("individual_password_reset_audit"), null);
    }

    public <O extends Record> IndividualPasswordResetAudit(Table<O> path, ForeignKey<O, IndividualPasswordResetAuditRecord> childPath, InverseForeignKey<O, IndividualPasswordResetAuditRecord> parentPath) {
        super(path, childPath, parentPath, INDIVIDUAL_PASSWORD_RESET_AUDIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndividualPasswordResetAuditPath extends IndividualPasswordResetAudit implements Path<IndividualPasswordResetAuditRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IndividualPasswordResetAuditPath(Table<O> path, ForeignKey<O, IndividualPasswordResetAuditRecord> childPath, InverseForeignKey<O, IndividualPasswordResetAuditRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndividualPasswordResetAuditPath(Name alias, Table<IndividualPasswordResetAuditRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndividualPasswordResetAuditPath as(String alias) {
            return new IndividualPasswordResetAuditPath(DSL.name(alias), this);
        }

        @Override
        public IndividualPasswordResetAuditPath as(Name alias) {
            return new IndividualPasswordResetAuditPath(alias, this);
        }

        @Override
        public IndividualPasswordResetAuditPath as(Table<?> alias) {
            return new IndividualPasswordResetAuditPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PASSWORD_RESET_INDIVIDUAL_ID, Indexes.IDX_PASSWORD_RESET_STATUS);
    }

    @Override
    public UniqueKey<IndividualPasswordResetAuditRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_PASSWORD_RESET_AUDIT_PKEY;
    }

    @Override
    public List<ForeignKey<IndividualPasswordResetAuditRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDIVIDUAL_PASSWORD_RESET_AUDIT__INDIVIDUAL_PASSWORD_RESET_AUDIT_INDIVIDUAL_ID_FKEY);
    }

    private transient IndividualPath _individual;

    /**
     * Get the implicit join path to the <code>individual</code> table.
     */
    public IndividualPath individual() {
        if (_individual == null)
            _individual = new IndividualPath(this, Keys.INDIVIDUAL_PASSWORD_RESET_AUDIT__INDIVIDUAL_PASSWORD_RESET_AUDIT_INDIVIDUAL_ID_FKEY, null);

        return _individual;
    }

    @Override
    public IndividualPasswordResetAudit as(String alias) {
        return new IndividualPasswordResetAudit(DSL.name(alias), this);
    }

    @Override
    public IndividualPasswordResetAudit as(Name alias) {
        return new IndividualPasswordResetAudit(alias, this);
    }

    @Override
    public IndividualPasswordResetAudit as(Table<?> alias) {
        return new IndividualPasswordResetAudit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPasswordResetAudit rename(String name) {
        return new IndividualPasswordResetAudit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPasswordResetAudit rename(Name name) {
        return new IndividualPasswordResetAudit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualPasswordResetAudit rename(Table<?> name) {
        return new IndividualPasswordResetAudit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit where(Condition condition) {
        return new IndividualPasswordResetAudit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPasswordResetAudit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPasswordResetAudit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPasswordResetAudit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualPasswordResetAudit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualPasswordResetAudit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
