/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Individual.IndividualPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualSessionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualSessions extends TableImpl<IndividualSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual_sessions</code>
     */
    public static final IndividualSessions INDIVIDUAL_SESSIONS = new IndividualSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualSessionsRecord> getRecordType() {
        return IndividualSessionsRecord.class;
    }

    /**
     * The column <code>individual_sessions.id</code>.
     */
    public final TableField<IndividualSessionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_sessions.individual_id</code>.
     */
    public final TableField<IndividualSessionsRecord, UUID> INDIVIDUAL_ID = createField(DSL.name("individual_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_sessions.accesstoken</code>.
     */
    public final TableField<IndividualSessionsRecord, String> ACCESSTOKEN = createField(DSL.name("accesstoken"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>individual_sessions.accesstoken_expirytime</code>.
     */
    public final TableField<IndividualSessionsRecord, LocalDateTime> ACCESSTOKEN_EXPIRYTIME = createField(DSL.name("accesstoken_expirytime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>individual_sessions.accesstoken_generated_on</code>.
     */
    public final TableField<IndividualSessionsRecord, LocalDateTime> ACCESSTOKEN_GENERATED_ON = createField(DSL.name("accesstoken_generated_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>individual_sessions.refreshtoken</code>.
     */
    public final TableField<IndividualSessionsRecord, String> REFRESHTOKEN = createField(DSL.name("refreshtoken"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>individual_sessions.refreshtoken_expirytime</code>.
     */
    public final TableField<IndividualSessionsRecord, LocalDateTime> REFRESHTOKEN_EXPIRYTIME = createField(DSL.name("refreshtoken_expirytime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>individual_sessions.refreshtoken_generated_on</code>.
     */
    public final TableField<IndividualSessionsRecord, LocalDateTime> REFRESHTOKEN_GENERATED_ON = createField(DSL.name("refreshtoken_generated_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>individual_sessions.ipaddress</code>.
     */
    public final TableField<IndividualSessionsRecord, String> IPADDRESS = createField(DSL.name("ipaddress"), SQLDataType.VARCHAR, this, "");

    private IndividualSessions(Name alias, Table<IndividualSessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndividualSessions(Name alias, Table<IndividualSessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual_sessions</code> table reference
     */
    public IndividualSessions(String alias) {
        this(DSL.name(alias), INDIVIDUAL_SESSIONS);
    }

    /**
     * Create an aliased <code>individual_sessions</code> table reference
     */
    public IndividualSessions(Name alias) {
        this(alias, INDIVIDUAL_SESSIONS);
    }

    /**
     * Create a <code>individual_sessions</code> table reference
     */
    public IndividualSessions() {
        this(DSL.name("individual_sessions"), null);
    }

    public <O extends Record> IndividualSessions(Table<O> path, ForeignKey<O, IndividualSessionsRecord> childPath, InverseForeignKey<O, IndividualSessionsRecord> parentPath) {
        super(path, childPath, parentPath, INDIVIDUAL_SESSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndividualSessionsPath extends IndividualSessions implements Path<IndividualSessionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IndividualSessionsPath(Table<O> path, ForeignKey<O, IndividualSessionsRecord> childPath, InverseForeignKey<O, IndividualSessionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndividualSessionsPath(Name alias, Table<IndividualSessionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndividualSessionsPath as(String alias) {
            return new IndividualSessionsPath(DSL.name(alias), this);
        }

        @Override
        public IndividualSessionsPath as(Name alias) {
            return new IndividualSessionsPath(alias, this);
        }

        @Override
        public IndividualSessionsPath as(Table<?> alias) {
            return new IndividualSessionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SESSIONS_ACCESSTOKEN, Indexes.IDX_SESSIONS_INDIVIDUAL_ID);
    }

    @Override
    public UniqueKey<IndividualSessionsRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_SESSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<IndividualSessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDIVIDUAL_SESSIONS__INDIVIDUAL_SESSIONS_IND_FK);
    }

    private transient IndividualPath _individual;

    /**
     * Get the implicit join path to the <code>individual</code> table.
     */
    public IndividualPath individual() {
        if (_individual == null)
            _individual = new IndividualPath(this, Keys.INDIVIDUAL_SESSIONS__INDIVIDUAL_SESSIONS_IND_FK, null);

        return _individual;
    }

    @Override
    public IndividualSessions as(String alias) {
        return new IndividualSessions(DSL.name(alias), this);
    }

    @Override
    public IndividualSessions as(Name alias) {
        return new IndividualSessions(alias, this);
    }

    @Override
    public IndividualSessions as(Table<?> alias) {
        return new IndividualSessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualSessions rename(String name) {
        return new IndividualSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualSessions rename(Name name) {
        return new IndividualSessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualSessions rename(Table<?> name) {
        return new IndividualSessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions where(Condition condition) {
        return new IndividualSessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualSessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualSessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualSessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualSessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualSessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
