/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Individual.IndividualPath;
import com.ganithyanthram.modularapp.db.jooq.tables.Roles.RolesPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.IndividualRoleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IndividualRole extends TableImpl<IndividualRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>individual_role</code>
     */
    public static final IndividualRole INDIVIDUAL_ROLE = new IndividualRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndividualRoleRecord> getRecordType() {
        return IndividualRoleRecord.class;
    }

    /**
     * The column <code>individual_role.id</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_role.individual_id</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> INDIVIDUAL_ID = createField(DSL.name("individual_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_role.role_id</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>individual_role.created_on</code>.
     */
    public final TableField<IndividualRoleRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>individual_role.updated_on</code>.
     */
    public final TableField<IndividualRoleRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>individual_role.created_by</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_role.updated_by</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>individual_role.org_id</code>.
     */
    public final TableField<IndividualRoleRecord, UUID> ORG_ID = createField(DSL.name("org_id"), SQLDataType.UUID, this, "");

    private IndividualRole(Name alias, Table<IndividualRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IndividualRole(Name alias, Table<IndividualRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>individual_role</code> table reference
     */
    public IndividualRole(String alias) {
        this(DSL.name(alias), INDIVIDUAL_ROLE);
    }

    /**
     * Create an aliased <code>individual_role</code> table reference
     */
    public IndividualRole(Name alias) {
        this(alias, INDIVIDUAL_ROLE);
    }

    /**
     * Create a <code>individual_role</code> table reference
     */
    public IndividualRole() {
        this(DSL.name("individual_role"), null);
    }

    public <O extends Record> IndividualRole(Table<O> path, ForeignKey<O, IndividualRoleRecord> childPath, InverseForeignKey<O, IndividualRoleRecord> parentPath) {
        super(path, childPath, parentPath, INDIVIDUAL_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IndividualRolePath extends IndividualRole implements Path<IndividualRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IndividualRolePath(Table<O> path, ForeignKey<O, IndividualRoleRecord> childPath, InverseForeignKey<O, IndividualRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IndividualRolePath(Name alias, Table<IndividualRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IndividualRolePath as(String alias) {
            return new IndividualRolePath(DSL.name(alias), this);
        }

        @Override
        public IndividualRolePath as(Name alias) {
            return new IndividualRolePath(alias, this);
        }

        @Override
        public IndividualRolePath as(Table<?> alias) {
            return new IndividualRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_INDIVIDUAL_ROLE_INDIVIDUAL_ID, Indexes.IDX_INDIVIDUAL_ROLE_ORG_ID, Indexes.IDX_INDIVIDUAL_ROLE_ROLE_ID);
    }

    @Override
    public UniqueKey<IndividualRoleRecord> getPrimaryKey() {
        return Keys.INDIVIDUAL_ROLE_ID_PK;
    }

    @Override
    public List<ForeignKey<IndividualRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INDIVIDUAL_ROLE__INDIVIDUAL_ROLE_INDIVIDUAL_ID_FK, Keys.INDIVIDUAL_ROLE__INDIVIDUAL_ROLE_ROLE_ID_FK);
    }

    private transient IndividualPath _individual;

    /**
     * Get the implicit join path to the <code>individual</code> table.
     */
    public IndividualPath individual() {
        if (_individual == null)
            _individual = new IndividualPath(this, Keys.INDIVIDUAL_ROLE__INDIVIDUAL_ROLE_INDIVIDUAL_ID_FK, null);

        return _individual;
    }

    private transient RolesPath _roles;

    /**
     * Get the implicit join path to the <code>roles</code> table.
     */
    public RolesPath roles() {
        if (_roles == null)
            _roles = new RolesPath(this, Keys.INDIVIDUAL_ROLE__INDIVIDUAL_ROLE_ROLE_ID_FK, null);

        return _roles;
    }

    @Override
    public IndividualRole as(String alias) {
        return new IndividualRole(DSL.name(alias), this);
    }

    @Override
    public IndividualRole as(Name alias) {
        return new IndividualRole(alias, this);
    }

    @Override
    public IndividualRole as(Table<?> alias) {
        return new IndividualRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualRole rename(String name) {
        return new IndividualRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualRole rename(Name name) {
        return new IndividualRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndividualRole rename(Table<?> name) {
        return new IndividualRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole where(Condition condition) {
        return new IndividualRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IndividualRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IndividualRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
