/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.ListNames.ListNamesPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.ListValuesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListValues extends TableImpl<ListValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>list_values</code>
     */
    public static final ListValues LIST_VALUES = new ListValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ListValuesRecord> getRecordType() {
        return ListValuesRecord.class;
    }

    /**
     * The column <code>list_values.id</code>.
     */
    public final TableField<ListValuesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>list_values.name</code>.
     */
    public final TableField<ListValuesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>list_values.list_names_id</code>.
     */
    public final TableField<ListValuesRecord, UUID> LIST_NAMES_ID = createField(DSL.name("list_names_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>list_values.is_active</code>.
     */
    public final TableField<ListValuesRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>list_values.created_by</code>.
     */
    public final TableField<ListValuesRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>list_values.updated_by</code>.
     */
    public final TableField<ListValuesRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>list_values.created_on</code>.
     */
    public final TableField<ListValuesRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>list_values.updated_on</code>.
     */
    public final TableField<ListValuesRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>list_values.code</code>.
     */
    public final TableField<ListValuesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50), this, "");

    private ListValues(Name alias, Table<ListValuesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ListValues(Name alias, Table<ListValuesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>list_values</code> table reference
     */
    public ListValues(String alias) {
        this(DSL.name(alias), LIST_VALUES);
    }

    /**
     * Create an aliased <code>list_values</code> table reference
     */
    public ListValues(Name alias) {
        this(alias, LIST_VALUES);
    }

    /**
     * Create a <code>list_values</code> table reference
     */
    public ListValues() {
        this(DSL.name("list_values"), null);
    }

    public <O extends Record> ListValues(Table<O> path, ForeignKey<O, ListValuesRecord> childPath, InverseForeignKey<O, ListValuesRecord> parentPath) {
        super(path, childPath, parentPath, LIST_VALUES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ListValuesPath extends ListValues implements Path<ListValuesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ListValuesPath(Table<O> path, ForeignKey<O, ListValuesRecord> childPath, InverseForeignKey<O, ListValuesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ListValuesPath(Name alias, Table<ListValuesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ListValuesPath as(String alias) {
            return new ListValuesPath(DSL.name(alias), this);
        }

        @Override
        public ListValuesPath as(Name alias) {
            return new ListValuesPath(alias, this);
        }

        @Override
        public ListValuesPath as(Table<?> alias) {
            return new ListValuesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LIST_VALUES_LIST_NAMES_ID);
    }

    @Override
    public UniqueKey<ListValuesRecord> getPrimaryKey() {
        return Keys.LIST_VALUES_PKEY;
    }

    @Override
    public List<ForeignKey<ListValuesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LIST_VALUES__FK_LIST_NAMES);
    }

    private transient ListNamesPath _listNames;

    /**
     * Get the implicit join path to the <code>list_names</code> table.
     */
    public ListNamesPath listNames() {
        if (_listNames == null)
            _listNames = new ListNamesPath(this, Keys.LIST_VALUES__FK_LIST_NAMES, null);

        return _listNames;
    }

    @Override
    public ListValues as(String alias) {
        return new ListValues(DSL.name(alias), this);
    }

    @Override
    public ListValues as(Name alias) {
        return new ListValues(alias, this);
    }

    @Override
    public ListValues as(Table<?> alias) {
        return new ListValues(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ListValues rename(String name) {
        return new ListValues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListValues rename(Name name) {
        return new ListValues(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListValues rename(Table<?> name) {
        return new ListValues(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues where(Condition condition) {
        return new ListValues(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListValues where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListValues where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListValues where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListValues where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListValues whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
