/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.ListValues.ListValuesPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.ListNamesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListNames extends TableImpl<ListNamesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>list_names</code>
     */
    public static final ListNames LIST_NAMES = new ListNames();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ListNamesRecord> getRecordType() {
        return ListNamesRecord.class;
    }

    /**
     * The column <code>list_names.id</code>.
     */
    public final TableField<ListNamesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>list_names.name</code>.
     */
    public final TableField<ListNamesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>list_names.is_active</code>.
     */
    public final TableField<ListNamesRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>list_names.created_by</code>.
     */
    public final TableField<ListNamesRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>list_names.updated_by</code>.
     */
    public final TableField<ListNamesRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>list_names.created_on</code>.
     */
    public final TableField<ListNamesRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>list_names.updated_on</code>.
     */
    public final TableField<ListNamesRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>list_names.is_statistics</code>.
     */
    public final TableField<ListNamesRecord, Boolean> IS_STATISTICS = createField(DSL.name("is_statistics"), SQLDataType.BOOLEAN, this, "");

    private ListNames(Name alias, Table<ListNamesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ListNames(Name alias, Table<ListNamesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>list_names</code> table reference
     */
    public ListNames(String alias) {
        this(DSL.name(alias), LIST_NAMES);
    }

    /**
     * Create an aliased <code>list_names</code> table reference
     */
    public ListNames(Name alias) {
        this(alias, LIST_NAMES);
    }

    /**
     * Create a <code>list_names</code> table reference
     */
    public ListNames() {
        this(DSL.name("list_names"), null);
    }

    public <O extends Record> ListNames(Table<O> path, ForeignKey<O, ListNamesRecord> childPath, InverseForeignKey<O, ListNamesRecord> parentPath) {
        super(path, childPath, parentPath, LIST_NAMES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ListNamesPath extends ListNames implements Path<ListNamesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ListNamesPath(Table<O> path, ForeignKey<O, ListNamesRecord> childPath, InverseForeignKey<O, ListNamesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ListNamesPath(Name alias, Table<ListNamesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ListNamesPath as(String alias) {
            return new ListNamesPath(DSL.name(alias), this);
        }

        @Override
        public ListNamesPath as(Name alias) {
            return new ListNamesPath(alias, this);
        }

        @Override
        public ListNamesPath as(Table<?> alias) {
            return new ListNamesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LIST_NAMES_NAME);
    }

    @Override
    public UniqueKey<ListNamesRecord> getPrimaryKey() {
        return Keys.LIST_NAMES_PKEY;
    }

    @Override
    public List<UniqueKey<ListNamesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LIST_NAMES_NAME_KEY);
    }

    private transient ListValuesPath _listValues;

    /**
     * Get the implicit to-many join path to the <code>list_values</code> table
     */
    public ListValuesPath listValues() {
        if (_listValues == null)
            _listValues = new ListValuesPath(this, null, Keys.LIST_VALUES__FK_LIST_NAMES.getInverseKey());

        return _listValues;
    }

    @Override
    public ListNames as(String alias) {
        return new ListNames(DSL.name(alias), this);
    }

    @Override
    public ListNames as(Name alias) {
        return new ListNames(alias, this);
    }

    @Override
    public ListNames as(Table<?> alias) {
        return new ListNames(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ListNames rename(String name) {
        return new ListNames(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListNames rename(Name name) {
        return new ListNames(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListNames rename(Table<?> name) {
        return new ListNames(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames where(Condition condition) {
        return new ListNames(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListNames where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListNames where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListNames where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ListNames where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ListNames whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
