/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Resource.ResourcePath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.ResourceRecord;
import com.ganithyanthram.modularapp.entitlement.common.converter.JsonbConverter;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Resource extends TableImpl<ResourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>resource</code>
     */
    public static final Resource RESOURCE = new Resource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResourceRecord> getRecordType() {
        return ResourceRecord.class;
    }

    /**
     * The column <code>resource.id</code>.
     */
    public final TableField<ResourceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>resource.name</code>.
     */
    public final TableField<ResourceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>resource.description</code>.
     */
    public final TableField<ResourceRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>resource.type</code>.
     */
    public final TableField<ResourceRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>resource.parent_resource_id</code>.
     */
    public final TableField<ResourceRecord, UUID> PARENT_RESOURCE_ID = createField(DSL.name("parent_resource_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>resource.validations</code>.
     */
    public final TableField<ResourceRecord, Map<String, Object>> VALIDATIONS = createField(DSL.name("validations"), SQLDataType.JSONB, this, "", new JsonbConverter());

    /**
     * The column <code>resource.is_active</code>.
     */
    public final TableField<ResourceRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>resource.created_on</code>.
     */
    public final TableField<ResourceRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>resource.updated_on</code>.
     */
    public final TableField<ResourceRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>resource.created_by</code>.
     */
    public final TableField<ResourceRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>resource.updated_by</code>.
     */
    public final TableField<ResourceRecord, UUID> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.UUID, this, "");

    private Resource(Name alias, Table<ResourceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Resource(Name alias, Table<ResourceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>resource</code> table reference
     */
    public Resource(String alias) {
        this(DSL.name(alias), RESOURCE);
    }

    /**
     * Create an aliased <code>resource</code> table reference
     */
    public Resource(Name alias) {
        this(alias, RESOURCE);
    }

    /**
     * Create a <code>resource</code> table reference
     */
    public Resource() {
        this(DSL.name("resource"), null);
    }

    public <O extends Record> Resource(Table<O> path, ForeignKey<O, ResourceRecord> childPath, InverseForeignKey<O, ResourceRecord> parentPath) {
        super(path, childPath, parentPath, RESOURCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ResourcePath extends Resource implements Path<ResourceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ResourcePath(Table<O> path, ForeignKey<O, ResourceRecord> childPath, InverseForeignKey<O, ResourceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ResourcePath(Name alias, Table<ResourceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ResourcePath as(String alias) {
            return new ResourcePath(DSL.name(alias), this);
        }

        @Override
        public ResourcePath as(Name alias) {
            return new ResourcePath(alias, this);
        }

        @Override
        public ResourcePath as(Table<?> alias) {
            return new ResourcePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_RESOURCE_PARENT_ID, Indexes.IDX_RESOURCE_TYPE);
    }

    @Override
    public UniqueKey<ResourceRecord> getPrimaryKey() {
        return Keys.RESOURCE_ID_PK;
    }

    @Override
    public List<ForeignKey<ResourceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RESOURCE__RESOURCE_PARENT_RESOURCE_FK);
    }

    private transient ResourcePath _resource;

    /**
     * Get the implicit join path to the <code>resource</code> table.
     */
    public ResourcePath resource() {
        if (_resource == null)
            _resource = new ResourcePath(this, Keys.RESOURCE__RESOURCE_PARENT_RESOURCE_FK, null);

        return _resource;
    }

    @Override
    public Resource as(String alias) {
        return new Resource(DSL.name(alias), this);
    }

    @Override
    public Resource as(Name alias) {
        return new Resource(alias, this);
    }

    @Override
    public Resource as(Table<?> alias) {
        return new Resource(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Resource rename(String name) {
        return new Resource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Resource rename(Name name) {
        return new Resource(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Resource rename(Table<?> name) {
        return new Resource(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource where(Condition condition) {
        return new Resource(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Resource where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Resource where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Resource where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Resource where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Resource whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
