/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables;


import com.ganithyanthram.modularapp.db.jooq.DefaultSchema;
import com.ganithyanthram.modularapp.db.jooq.Indexes;
import com.ganithyanthram.modularapp.db.jooq.Keys;
import com.ganithyanthram.modularapp.db.jooq.tables.Users.UsersPath;
import com.ganithyanthram.modularapp.db.jooq.tables.records.UserProfilesRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserProfiles extends TableImpl<UserProfilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_profiles</code>
     */
    public static final UserProfiles USER_PROFILES = new UserProfiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserProfilesRecord> getRecordType() {
        return UserProfilesRecord.class;
    }

    /**
     * The column <code>user_profiles.id</code>.
     */
    public final TableField<UserProfilesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>user_profiles.user_id</code>.
     */
    public final TableField<UserProfilesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>user_profiles.bio</code>.
     */
    public final TableField<UserProfilesRecord, String> BIO = createField(DSL.name("bio"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>user_profiles.avatar_url</code>.
     */
    public final TableField<UserProfilesRecord, String> AVATAR_URL = createField(DSL.name("avatar_url"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>user_profiles.phone_number</code>.
     */
    public final TableField<UserProfilesRecord, String> PHONE_NUMBER = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>user_profiles.date_of_birth</code>.
     */
    public final TableField<UserProfilesRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>user_profiles.metadata</code>.
     */
    public final TableField<UserProfilesRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>user_profiles.created_at</code>.
     */
    public final TableField<UserProfilesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>user_profiles.updated_at</code>.
     */
    public final TableField<UserProfilesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private UserProfiles(Name alias, Table<UserProfilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserProfiles(Name alias, Table<UserProfilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>user_profiles</code> table reference
     */
    public UserProfiles(String alias) {
        this(DSL.name(alias), USER_PROFILES);
    }

    /**
     * Create an aliased <code>user_profiles</code> table reference
     */
    public UserProfiles(Name alias) {
        this(alias, USER_PROFILES);
    }

    /**
     * Create a <code>user_profiles</code> table reference
     */
    public UserProfiles() {
        this(DSL.name("user_profiles"), null);
    }

    public <O extends Record> UserProfiles(Table<O> path, ForeignKey<O, UserProfilesRecord> childPath, InverseForeignKey<O, UserProfilesRecord> parentPath) {
        super(path, childPath, parentPath, USER_PROFILES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserProfilesPath extends UserProfiles implements Path<UserProfilesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserProfilesPath(Table<O> path, ForeignKey<O, UserProfilesRecord> childPath, InverseForeignKey<O, UserProfilesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserProfilesPath(Name alias, Table<UserProfilesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserProfilesPath as(String alias) {
            return new UserProfilesPath(DSL.name(alias), this);
        }

        @Override
        public UserProfilesPath as(Name alias) {
            return new UserProfilesPath(alias, this);
        }

        @Override
        public UserProfilesPath as(Table<?> alias) {
            return new UserProfilesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_PROFILES_USER_ID);
    }

    @Override
    public UniqueKey<UserProfilesRecord> getPrimaryKey() {
        return Keys.USER_PROFILES_PKEY;
    }

    @Override
    public List<ForeignKey<UserProfilesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_PROFILES__FK_USER_PROFILES_USER_ID);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_PROFILES__FK_USER_PROFILES_USER_ID, null);

        return _users;
    }

    @Override
    public UserProfiles as(String alias) {
        return new UserProfiles(DSL.name(alias), this);
    }

    @Override
    public UserProfiles as(Name alias) {
        return new UserProfiles(alias, this);
    }

    @Override
    public UserProfiles as(Table<?> alias) {
        return new UserProfiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfiles rename(String name) {
        return new UserProfiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfiles rename(Name name) {
        return new UserProfiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserProfiles rename(Table<?> name) {
        return new UserProfiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles where(Condition condition) {
        return new UserProfiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserProfiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserProfiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
