/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq;


import com.ganithyanthram.modularapp.db.jooq.tables.Individual;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPasswordResetAudit;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualPermission;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualRole;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualSessions;
import com.ganithyanthram.modularapp.db.jooq.tables.IndividualVerificationAudit;
import com.ganithyanthram.modularapp.db.jooq.tables.ListNames;
import com.ganithyanthram.modularapp.db.jooq.tables.ListValues;
import com.ganithyanthram.modularapp.db.jooq.tables.Organisation;
import com.ganithyanthram.modularapp.db.jooq.tables.Resource;
import com.ganithyanthram.modularapp.db.jooq.tables.Roles;
import com.ganithyanthram.modularapp.db.jooq.tables.UserProfiles;
import com.ganithyanthram.modularapp.db.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>individual</code>.
     */
    public final Individual INDIVIDUAL = Individual.INDIVIDUAL;

    /**
     * The table <code>individual_password_reset_audit</code>.
     */
    public final IndividualPasswordResetAudit INDIVIDUAL_PASSWORD_RESET_AUDIT = IndividualPasswordResetAudit.INDIVIDUAL_PASSWORD_RESET_AUDIT;

    /**
     * The table <code>individual_permission</code>.
     */
    public final IndividualPermission INDIVIDUAL_PERMISSION = IndividualPermission.INDIVIDUAL_PERMISSION;

    /**
     * The table <code>individual_role</code>.
     */
    public final IndividualRole INDIVIDUAL_ROLE = IndividualRole.INDIVIDUAL_ROLE;

    /**
     * The table <code>individual_sessions</code>.
     */
    public final IndividualSessions INDIVIDUAL_SESSIONS = IndividualSessions.INDIVIDUAL_SESSIONS;

    /**
     * The table <code>individual_verification_audit</code>.
     */
    public final IndividualVerificationAudit INDIVIDUAL_VERIFICATION_AUDIT = IndividualVerificationAudit.INDIVIDUAL_VERIFICATION_AUDIT;

    /**
     * The table <code>list_names</code>.
     */
    public final ListNames LIST_NAMES = ListNames.LIST_NAMES;

    /**
     * The table <code>list_values</code>.
     */
    public final ListValues LIST_VALUES = ListValues.LIST_VALUES;

    /**
     * The table <code>organisation</code>.
     */
    public final Organisation ORGANISATION = Organisation.ORGANISATION;

    /**
     * The table <code>resource</code>.
     */
    public final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>user_profiles</code>.
     */
    public final UserProfiles USER_PROFILES = UserProfiles.USER_PROFILES;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Individual.INDIVIDUAL,
            IndividualPasswordResetAudit.INDIVIDUAL_PASSWORD_RESET_AUDIT,
            IndividualPermission.INDIVIDUAL_PERMISSION,
            IndividualRole.INDIVIDUAL_ROLE,
            IndividualSessions.INDIVIDUAL_SESSIONS,
            IndividualVerificationAudit.INDIVIDUAL_VERIFICATION_AUDIT,
            ListNames.LIST_NAMES,
            ListValues.LIST_VALUES,
            Organisation.ORGANISATION,
            Resource.RESOURCE,
            Roles.ROLES,
            UserProfiles.USER_PROFILES,
            Users.USERS
        );
    }
}
