/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq;


import com.ganithyanthram.modularapp.db.jooq.tables.UserProfiles;
import com.ganithyanthram.modularapp.db.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>user_profiles</code>.
     */
    public static final UserProfiles USER_PROFILES = UserProfiles.USER_PROFILES;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
