/*
 * This file is generated by jOOQ.
 */
package com.ganithyanthram.modularapp.db.jooq.tables.daos;


import com.ganithyanthram.modularapp.db.jooq.tables.UserProfiles;
import com.ganithyanthram.modularapp.db.jooq.tables.records.UserProfilesRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class UserProfilesDao extends DAOImpl<UserProfilesRecord, com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles, UUID> {

    /**
     * Create a new UserProfilesDao without any configuration
     */
    public UserProfilesDao() {
        super(UserProfiles.USER_PROFILES, com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles.class);
    }

    /**
     * Create a new UserProfilesDao with an attached configuration
     */
    @Autowired
    public UserProfilesDao(Configuration configuration) {
        super(UserProfiles.USER_PROFILES, com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles.class, configuration);
    }

    @Override
    public UUID getId(com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchById(UUID... values) {
        return fetch(UserProfiles.USER_PROFILES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles fetchOneById(UUID value) {
        return fetchOne(UserProfiles.USER_PROFILES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchOptionalById(UUID value) {
        return fetchOptional(UserProfiles.USER_PROFILES.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfUserId(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByUserId(UUID... values) {
        return fetch(UserProfiles.USER_PROFILES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>bio BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfBio(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.BIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bio IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByBio(String... values) {
        return fetch(UserProfiles.USER_PROFILES.BIO, values);
    }

    /**
     * Fetch records that have <code>avatar_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfAvatarUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.AVATAR_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>avatar_url IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByAvatarUrl(String... values) {
        return fetch(UserProfiles.USER_PROFILES.AVATAR_URL, values);
    }

    /**
     * Fetch records that have <code>phone_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfPhoneNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.PHONE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_number IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByPhoneNumber(String... values) {
        return fetch(UserProfiles.USER_PROFILES.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>date_of_birth BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfDateOfBirth(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.DATE_OF_BIRTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date_of_birth IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByDateOfBirth(LocalDate... values) {
        return fetch(UserProfiles.USER_PROFILES.DATE_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>metadata BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfMetadata(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.METADATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>metadata IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByMetadata(JSONB... values) {
        return fetch(UserProfiles.USER_PROFILES.METADATA, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(UserProfiles.USER_PROFILES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserProfiles.USER_PROFILES.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.ganithyanthram.modularapp.db.jooq.tables.pojos.UserProfiles> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(UserProfiles.USER_PROFILES.UPDATED_AT, values);
    }
}
